// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPSkHJoxw62_MPBsCGoFWfrJMh1mwzMZM',
    appId: '1:782451380308:android:c58f8e92db2e1db15d5dc1',
    messagingSenderId: '782451380308',
    projectId: 'yogi-face',
    storageBucket: 'yogi-face.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUR2k9EJJXEi2S33Ci1-pwYFp_LdZ6WW4',
    appId: '1:782451380308:ios:11d3e02c43df08425d5dc1',
    messagingSenderId: '782451380308',
    projectId: 'yogi-face',
    storageBucket: 'yogi-face.firebasestorage.app',
    androidClientId: '782451380308-1o4f27ogt120apgacejh9vn84p8daifm.apps.googleusercontent.com',
    iosClientId: '782451380308-rdbnfp2kbqaag497shimkandplga5oc0.apps.googleusercontent.com',
    iosBundleId: 'com.flywork.yogifaceapp',
  );

}